import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const monteSerat = Montserrat({
  variable: "--font-monteserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${monteSerat.variable} antialiased`}>
        <div className="flex flex-col bg-slate-900/10 h-dvh overflow-y-auto">
          <Header />
          <main className=" min-h-dvh px-24 py-8 mt-16 ">{children}</main>
        </div>
      </body>
    </html>
  );
}
